# Generated by Django 4.2.5 on 2025-08-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_price_alter_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='media/img/Main.jpg', help_text='Upload a category image (optional)', null=True, upload_to='uploads/categories/'),
        ),
    ]
