# Generated by Django 4.2.5 on 2025-08-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a category image (optional)', null=True, upload_to='uploads/categories/'),
        ),
    ]
