# Generated by Django 4.2.5 on 2025-08-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_remove_paymentorder_shipping_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
