# Generated by Django 4.2.5 on 2025-08-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_alter_shippingaddress_shipping_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_email',
            field=models.CharField(default='no-email@example.com', max_length=255),
            preserve_default=False,
        ),
    ]
